// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/msg.proto

package com.yue;

public final class Msg {
  private Msg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Packet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Packet.Type type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.Packet.Type type = 1;</code>
     * @return The type.
     */
    com.yue.Msg.Packet.Type getType();

    /**
     * <code>int32 srcId = 2;</code>
     * @return The srcId.
     */
    int getSrcId();

    /**
     * <code>int32 dstId = 3;</code>
     * @return The dstId.
     */
    int getDstId();

    /**
     * <code>string content = 4;</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <code>string content = 4;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>map&lt;string, string&gt; extra = 5;</code>
     */
    int getExtraCount();
    /**
     * <code>map&lt;string, string&gt; extra = 5;</code>
     */
    boolean containsExtra(
        java.lang.String key);
    /**
     * Use {@link #getExtraMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getExtra();
    /**
     * <code>map&lt;string, string&gt; extra = 5;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getExtraMap();
    /**
     * <code>map&lt;string, string&gt; extra = 5;</code>
     */

    java.lang.String getExtraOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; extra = 5;</code>
     */

    java.lang.String getExtraOrThrow(
        java.lang.String key);

    /**
     * <code>string debugInfo = 6;</code>
     * @return The debugInfo.
     */
    java.lang.String getDebugInfo();
    /**
     * <code>string debugInfo = 6;</code>
     * @return The bytes for debugInfo.
     */
    com.google.protobuf.ByteString
        getDebugInfoBytes();
  }
  /**
   * Protobuf type {@code Packet}
   */
  public static final class Packet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Packet)
      PacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Packet.newBuilder() to construct.
    private Packet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Packet() {
      type_ = 0;
      content_ = "";
      debugInfo_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Packet();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Packet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 16: {

              srcId_ = input.readInt32();
              break;
            }
            case 24: {

              dstId_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                extra_ = com.google.protobuf.MapField.newMapField(
                    ExtraDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              extra__ = input.readMessage(
                  ExtraDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              extra_.getMutableMap().put(
                  extra__.getKey(), extra__.getValue());
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              debugInfo_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yue.Msg.internal_static_Packet_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetExtra();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yue.Msg.internal_static_Packet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yue.Msg.Packet.class, com.yue.Msg.Packet.Builder.class);
    }

    /**
     * Protobuf enum {@code Packet.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>JOIN = 0;</code>
       */
      JOIN(0),
      /**
       * <code>LEAVE = 1;</code>
       */
      LEAVE(1),
      /**
       * <pre>
       * source -&gt; rp
       * </pre>
       *
       * <code>MULTICAST_TUNNELING = 2;</code>
       */
      MULTICAST_TUNNELING(2),
      /**
       * <pre>
       * rp -&gt; subscribers
       * </pre>
       *
       * <code>MULTICAST_FLOODING = 3;</code>
       */
      MULTICAST_FLOODING(3),
      /**
       * <code>PRUNE = 4;</code>
       */
      PRUNE(4),
      /**
       * <code>REVERSE_TUNNELING = 5;</code>
       */
      REVERSE_TUNNELING(5),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>JOIN = 0;</code>
       */
      public static final int JOIN_VALUE = 0;
      /**
       * <code>LEAVE = 1;</code>
       */
      public static final int LEAVE_VALUE = 1;
      /**
       * <pre>
       * source -&gt; rp
       * </pre>
       *
       * <code>MULTICAST_TUNNELING = 2;</code>
       */
      public static final int MULTICAST_TUNNELING_VALUE = 2;
      /**
       * <pre>
       * rp -&gt; subscribers
       * </pre>
       *
       * <code>MULTICAST_FLOODING = 3;</code>
       */
      public static final int MULTICAST_FLOODING_VALUE = 3;
      /**
       * <code>PRUNE = 4;</code>
       */
      public static final int PRUNE_VALUE = 4;
      /**
       * <code>REVERSE_TUNNELING = 5;</code>
       */
      public static final int REVERSE_TUNNELING_VALUE = 5;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Type forNumber(int value) {
        switch (value) {
          case 0: return JOIN;
          case 1: return LEAVE;
          case 2: return MULTICAST_TUNNELING;
          case 3: return MULTICAST_FLOODING;
          case 4: return PRUNE;
          case 5: return REVERSE_TUNNELING;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.yue.Msg.Packet.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Packet.Type)
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.Packet.Type type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.Packet.Type type = 1;</code>
     * @return The type.
     */
    @java.lang.Override public com.yue.Msg.Packet.Type getType() {
      @SuppressWarnings("deprecation")
      com.yue.Msg.Packet.Type result = com.yue.Msg.Packet.Type.valueOf(type_);
      return result == null ? com.yue.Msg.Packet.Type.UNRECOGNIZED : result;
    }

    public static final int SRCID_FIELD_NUMBER = 2;
    private int srcId_;
    /**
     * <code>int32 srcId = 2;</code>
     * @return The srcId.
     */
    @java.lang.Override
    public int getSrcId() {
      return srcId_;
    }

    public static final int DSTID_FIELD_NUMBER = 3;
    private int dstId_;
    /**
     * <code>int32 dstId = 3;</code>
     * @return The dstId.
     */
    @java.lang.Override
    public int getDstId() {
      return dstId_;
    }

    public static final int CONTENT_FIELD_NUMBER = 4;
    private volatile java.lang.Object content_;
    /**
     * <code>string content = 4;</code>
     * @return The content.
     */
    @java.lang.Override
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 4;</code>
     * @return The bytes for content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXTRA_FIELD_NUMBER = 5;
    private static final class ExtraDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.yue.Msg.internal_static_Packet_ExtraEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> extra_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetExtra() {
      if (extra_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ExtraDefaultEntryHolder.defaultEntry);
      }
      return extra_;
    }

    public int getExtraCount() {
      return internalGetExtra().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; extra = 5;</code>
     */

    @java.lang.Override
    public boolean containsExtra(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetExtra().getMap().containsKey(key);
    }
    /**
     * Use {@link #getExtraMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getExtra() {
      return getExtraMap();
    }
    /**
     * <code>map&lt;string, string&gt; extra = 5;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getExtraMap() {
      return internalGetExtra().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; extra = 5;</code>
     */
    @java.lang.Override

    public java.lang.String getExtraOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetExtra().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; extra = 5;</code>
     */
    @java.lang.Override

    public java.lang.String getExtraOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetExtra().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int DEBUGINFO_FIELD_NUMBER = 6;
    private volatile java.lang.Object debugInfo_;
    /**
     * <code>string debugInfo = 6;</code>
     * @return The debugInfo.
     */
    @java.lang.Override
    public java.lang.String getDebugInfo() {
      java.lang.Object ref = debugInfo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        debugInfo_ = s;
        return s;
      }
    }
    /**
     * <code>string debugInfo = 6;</code>
     * @return The bytes for debugInfo.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDebugInfoBytes() {
      java.lang.Object ref = debugInfo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        debugInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != com.yue.Msg.Packet.Type.JOIN.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (srcId_ != 0) {
        output.writeInt32(2, srcId_);
      }
      if (dstId_ != 0) {
        output.writeInt32(3, dstId_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, content_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetExtra(),
          ExtraDefaultEntryHolder.defaultEntry,
          5);
      if (!getDebugInfoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, debugInfo_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != com.yue.Msg.Packet.Type.JOIN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (srcId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, srcId_);
      }
      if (dstId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, dstId_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, content_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetExtra().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        extra__ = ExtraDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(5, extra__);
      }
      if (!getDebugInfoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, debugInfo_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yue.Msg.Packet)) {
        return super.equals(obj);
      }
      com.yue.Msg.Packet other = (com.yue.Msg.Packet) obj;

      if (type_ != other.type_) return false;
      if (getSrcId()
          != other.getSrcId()) return false;
      if (getDstId()
          != other.getDstId()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!internalGetExtra().equals(
          other.internalGetExtra())) return false;
      if (!getDebugInfo()
          .equals(other.getDebugInfo())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + SRCID_FIELD_NUMBER;
      hash = (53 * hash) + getSrcId();
      hash = (37 * hash) + DSTID_FIELD_NUMBER;
      hash = (53 * hash) + getDstId();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      if (!internalGetExtra().getMap().isEmpty()) {
        hash = (37 * hash) + EXTRA_FIELD_NUMBER;
        hash = (53 * hash) + internalGetExtra().hashCode();
      }
      hash = (37 * hash) + DEBUGINFO_FIELD_NUMBER;
      hash = (53 * hash) + getDebugInfo().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yue.Msg.Packet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yue.Msg.Packet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yue.Msg.Packet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yue.Msg.Packet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yue.Msg.Packet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yue.Msg.Packet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yue.Msg.Packet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yue.Msg.Packet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yue.Msg.Packet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yue.Msg.Packet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yue.Msg.Packet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yue.Msg.Packet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yue.Msg.Packet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Packet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Packet)
        com.yue.Msg.PacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yue.Msg.internal_static_Packet_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetExtra();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetMutableExtra();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yue.Msg.internal_static_Packet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yue.Msg.Packet.class, com.yue.Msg.Packet.Builder.class);
      }

      // Construct using com.yue.Msg.Packet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        srcId_ = 0;

        dstId_ = 0;

        content_ = "";

        internalGetMutableExtra().clear();
        debugInfo_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yue.Msg.internal_static_Packet_descriptor;
      }

      @java.lang.Override
      public com.yue.Msg.Packet getDefaultInstanceForType() {
        return com.yue.Msg.Packet.getDefaultInstance();
      }

      @java.lang.Override
      public com.yue.Msg.Packet build() {
        com.yue.Msg.Packet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.yue.Msg.Packet buildPartial() {
        com.yue.Msg.Packet result = new com.yue.Msg.Packet(this);
        int from_bitField0_ = bitField0_;
        result.type_ = type_;
        result.srcId_ = srcId_;
        result.dstId_ = dstId_;
        result.content_ = content_;
        result.extra_ = internalGetExtra();
        result.extra_.makeImmutable();
        result.debugInfo_ = debugInfo_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yue.Msg.Packet) {
          return mergeFrom((com.yue.Msg.Packet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yue.Msg.Packet other) {
        if (other == com.yue.Msg.Packet.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getSrcId() != 0) {
          setSrcId(other.getSrcId());
        }
        if (other.getDstId() != 0) {
          setDstId(other.getDstId());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        internalGetMutableExtra().mergeFrom(
            other.internalGetExtra());
        if (!other.getDebugInfo().isEmpty()) {
          debugInfo_ = other.debugInfo_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yue.Msg.Packet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yue.Msg.Packet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>.Packet.Type type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.Packet.Type type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Packet.Type type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public com.yue.Msg.Packet.Type getType() {
        @SuppressWarnings("deprecation")
        com.yue.Msg.Packet.Type result = com.yue.Msg.Packet.Type.valueOf(type_);
        return result == null ? com.yue.Msg.Packet.Type.UNRECOGNIZED : result;
      }
      /**
       * <code>.Packet.Type type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(com.yue.Msg.Packet.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Packet.Type type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int srcId_ ;
      /**
       * <code>int32 srcId = 2;</code>
       * @return The srcId.
       */
      @java.lang.Override
      public int getSrcId() {
        return srcId_;
      }
      /**
       * <code>int32 srcId = 2;</code>
       * @param value The srcId to set.
       * @return This builder for chaining.
       */
      public Builder setSrcId(int value) {
        
        srcId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 srcId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSrcId() {
        
        srcId_ = 0;
        onChanged();
        return this;
      }

      private int dstId_ ;
      /**
       * <code>int32 dstId = 3;</code>
       * @return The dstId.
       */
      @java.lang.Override
      public int getDstId() {
        return dstId_;
      }
      /**
       * <code>int32 dstId = 3;</code>
       * @param value The dstId to set.
       * @return This builder for chaining.
       */
      public Builder setDstId(int value) {
        
        dstId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 dstId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDstId() {
        
        dstId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>string content = 4;</code>
       * @return The content.
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string content = 4;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 4;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 4;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> extra_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetExtra() {
        if (extra_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ExtraDefaultEntryHolder.defaultEntry);
        }
        return extra_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableExtra() {
        onChanged();;
        if (extra_ == null) {
          extra_ = com.google.protobuf.MapField.newMapField(
              ExtraDefaultEntryHolder.defaultEntry);
        }
        if (!extra_.isMutable()) {
          extra_ = extra_.copy();
        }
        return extra_;
      }

      public int getExtraCount() {
        return internalGetExtra().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; extra = 5;</code>
       */

      @java.lang.Override
      public boolean containsExtra(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetExtra().getMap().containsKey(key);
      }
      /**
       * Use {@link #getExtraMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getExtra() {
        return getExtraMap();
      }
      /**
       * <code>map&lt;string, string&gt; extra = 5;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, java.lang.String> getExtraMap() {
        return internalGetExtra().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; extra = 5;</code>
       */
      @java.lang.Override

      public java.lang.String getExtraOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetExtra().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; extra = 5;</code>
       */
      @java.lang.Override

      public java.lang.String getExtraOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetExtra().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearExtra() {
        internalGetMutableExtra().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; extra = 5;</code>
       */

      public Builder removeExtra(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableExtra().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableExtra() {
        return internalGetMutableExtra().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; extra = 5;</code>
       */
      public Builder putExtra(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableExtra().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; extra = 5;</code>
       */

      public Builder putAllExtra(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableExtra().getMutableMap()
            .putAll(values);
        return this;
      }

      private java.lang.Object debugInfo_ = "";
      /**
       * <code>string debugInfo = 6;</code>
       * @return The debugInfo.
       */
      public java.lang.String getDebugInfo() {
        java.lang.Object ref = debugInfo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          debugInfo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string debugInfo = 6;</code>
       * @return The bytes for debugInfo.
       */
      public com.google.protobuf.ByteString
          getDebugInfoBytes() {
        java.lang.Object ref = debugInfo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          debugInfo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string debugInfo = 6;</code>
       * @param value The debugInfo to set.
       * @return This builder for chaining.
       */
      public Builder setDebugInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        debugInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string debugInfo = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearDebugInfo() {
        
        debugInfo_ = getDefaultInstance().getDebugInfo();
        onChanged();
        return this;
      }
      /**
       * <code>string debugInfo = 6;</code>
       * @param value The bytes for debugInfo to set.
       * @return This builder for chaining.
       */
      public Builder setDebugInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        debugInfo_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Packet)
    }

    // @@protoc_insertion_point(class_scope:Packet)
    private static final com.yue.Msg.Packet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yue.Msg.Packet();
    }

    public static com.yue.Msg.Packet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Packet>
        PARSER = new com.google.protobuf.AbstractParser<Packet>() {
      @java.lang.Override
      public Packet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Packet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Packet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Packet> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.yue.Msg.Packet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Packet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Packet_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Packet_ExtraEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Packet_ExtraEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017proto/msg.proto\"\247\002\n\006Packet\022\032\n\004type\030\001 \001" +
      "(\0162\014.Packet.Type\022\r\n\005srcId\030\002 \001(\005\022\r\n\005dstId" +
      "\030\003 \001(\005\022\017\n\007content\030\004 \001(\t\022!\n\005extra\030\005 \003(\0132\022" +
      ".Packet.ExtraEntry\022\021\n\tdebugInfo\030\006 \001(\t\032,\n" +
      "\nExtraEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:" +
      "\0028\001\"n\n\004Type\022\010\n\004JOIN\020\000\022\t\n\005LEAVE\020\001\022\027\n\023MULT" +
      "ICAST_TUNNELING\020\002\022\026\n\022MULTICAST_FLOODING\020" +
      "\003\022\t\n\005PRUNE\020\004\022\025\n\021REVERSE_TUNNELING\020\005B\t\n\007c" +
      "om.yueb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Packet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Packet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Packet_descriptor,
        new java.lang.String[] { "Type", "SrcId", "DstId", "Content", "Extra", "DebugInfo", });
    internal_static_Packet_ExtraEntry_descriptor =
      internal_static_Packet_descriptor.getNestedTypes().get(0);
    internal_static_Packet_ExtraEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Packet_ExtraEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
